[tool.black]
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
  migrations/*
)/
| ^/manage.py
'''
[tool.isort]
py_version=39
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = ["core/migrations/",]
